### ISSUE TITLE
timeline bug

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/fintwit-bot#551]
Traceback (most recent call last):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 198, in _loop
    raise exc
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 137, in get_latest_tweet
    await self.on_data(tweet, update_tweet_id=True)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 149, in on_data
    formatted_tweet = parse_tweet(tweet, update_tweet_id=update_tweet_id)
  File "/home/akkie100/fintwit-bot/src/util/parse_tweet.py", line 183, in parse_tweet
    (
TypeError: cannot unpack non-iterable NoneType object

**Comment by StephanAkkerman** [comment]
Unhandled exception in internal background task 'get_latest_tweet'.
Traceback (most recent call last):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 137, in get_latest_tweet
    await self.on_data(tweet, update_tweet_id=True)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 149, in on_data
    formatted_tweet = parse_tweet(tweet, update_tweet_id=update_tweet_id)
  File "/home/akkie100/fintwit-bot/src/util/parse_tweet.py", line 194, in parse_tweet
    ) = parse_tweet(result)
  File "/home/akkie100/fintwit-bot/src/util/parse_tweet.py", line 130, in parse_tweet
    user_name = get_user_info(tweet, "name")  # The name of the account (not @username)
  File "/home/akkie100/fintwit-bot/src/util/parse_tweet.py", line 29, in get_user_info
    return tweet["core"]["user_results"]["result"]["legacy"][key]
KeyError: 'legacy'

**Comment by StephanAkkerman** [comment]
Could be because of recent changes to #474
