### ISSUE TITLE
Catch discord errors

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/fintwit-bot#584]
Traceback (most recent call last):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/tasks/__init__.py", line 169, in _loop
    await self.coro(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 144, in get_latest_tweet
    await self.on_data(tweet, update_tweet_id=True)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 172, in on_data
    e, category, base_symbols = await make_tweet_embed(
  File "/home/akkie100/fintwit-bot/src/util/tweet_embed.py", line 80, in make_tweet_embed
    e, category, base_symbols = await add_financials(
  File "/home/akkie100/fintwit-bot/src/util/tweet_embed.py", line 331, in add_financials
    await tweet_overview.overview(category, base_symbols, prediction)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/overview.py", line 59, in overview
    await self.make_overview(category, tickers, sentiment)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/overview.py", line 181, in make_overview
    await self.crypto_channel.purge(limit=1)
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/channel.py", line 456, in purge
    return await discord.abc._purge_messages_helper(
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/abc.py", line 176, in _purge_messages_helper
    await ret[-1].delete(reason=reason)
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/message.py", line 1365, in delete
    await del_func
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/http.py", line 371, in request
    raise DiscordServerError(response, data)
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Comment by StephanAkkerman** [comment]
This would add a lot of try: except to all Discord related lines

**Comment by StephanAkkerman** [comment]
Add code like:
```python
@global_overview.error
    async def overview_error(self, error: Exception):
        logging.error(f"Error in global_overview loop: {error}")
```

To handle errors in loops
